let dataStructure = [
    {
      day:"1",
      content:"./assets/jul.jpg",
      "type":"image",
      "sound": './assets/doorSound.mp3'
    },
    {
      day:"2",
      content:"https://www.youtube.com/embed/r5jid6j12h8?si=Mio_osNsGNXYTJ_o",
      "type":"video"
    },
    {
      day:"3",
      content:"./assets/jul.jpg",
      "type":"image"
    },
    {
      day:"4",
      content:"./assets/jul.jpg"
    },
    {
      day:"5",
      content:"./assets/jul.jpg"
    },
    {
      day:"6",
      content:"./assets/jul.jpg"
    },
    {
      day:"7",
      content:"./assets/jul.jpg"
    },
    {
      day:"8",
      content:"./assets/jul.jpg"
    },
    {
      day:"9",
      content:"./assets/jul.jpg"
    },
  ] 